#!/bin/bash
set -e

# Update frontend/.env from the canonical env file written by deploy-testnet.sh.
# Usage: ./scripts/update-frontend-env.sh [testnet|mainnet]
#
# The canonical env file (.env.testnet or .env.mainnet) is the single source
# of truth for FACTORY_CONTRACT_ID and STELLAR_NETWORK.
# See docs/PRODUCTION_INTEGRATION_RUNBOOK.md for the full deployment sequence.

NETWORK="${1:-testnet}"
CANONICAL_ENV=".env.${NETWORK}"

# Fall back to legacy deployment-testnet.json if canonical env is absent
if [ -f "$CANONICAL_ENV" ]; then
  # shellcheck disable=SC1090
  set -a; source "$CANONICAL_ENV"; set +a
  CONTRACT_ID="${FACTORY_CONTRACT_ID}"
elif [ -f "deployment-${NETWORK}.json" ]; then
  CONTRACT_ID=$(grep -o '"contractId": "[^"]*' "deployment-${NETWORK}.json" | cut -d'"' -f4)
else
  echo "Error: neither $CANONICAL_ENV nor deployment-${NETWORK}.json found."
  echo "Deploy the contract first: ./scripts/deploy-testnet.sh"
  exit 1
fi

if [ -z "$CONTRACT_ID" ]; then
  echo "Error: FACTORY_CONTRACT_ID is empty in $CANONICAL_ENV"
  exit 1
fi

echo "Updating frontend/.env for network=${NETWORK}, contract=${CONTRACT_ID}"

cat > frontend/.env <<EOF
# Auto-generated by update-frontend-env.sh — do not edit manually.
# Re-run this script after each deployment to keep values in sync.
# See docs/PRODUCTION_INTEGRATION_RUNBOOK.md

VITE_FACTORY_CONTRACT_ID=${CONTRACT_ID}
VITE_NETWORK=${NETWORK}

# IPFS Configuration (optional — required for token metadata uploads)
VITE_IPFS_API_KEY=
VITE_IPFS_API_SECRET=
EOF

echo "frontend/.env updated successfully."
